--
-- VHDL Test Bench DigTech4_lib.bin2bcd_tester.bin2bcd_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 12:39:37 02/04/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY bin2bcd_tester IS
   GENERIC (
      bin_width : integer := 6
   );
   PORT (
      clk_in        : OUT    std_logic;
      rst_in        : OUT    std_logic;
      start_conv_in : OUT    std_logic;
      bin_in        : OUT    unsigned(bin_width-1 downto 0);--std_logic_vector((bin_width-1) downto 0);
      conv_rdy_out  : IN     std_logic;
      bcd_out       : IN     unsigned(7 downto 0)--std_logic_vector(7 downto 0)
   );
END bin2bcd_tester;


LIBRARY DigTech4_lib;

ARCHITECTURE rtl OF bin2bcd_tester IS
  signal bin: integer;
   -- Architecture declarations
BEGIN
    process begin
    while(true) loop
      clk_in <= '0';
      wait for 5ns;
      clk_in <= '1';
      wait for 5ns;
  end loop;
  wait;
  end process;
  
  process begin  
      rst_in <= '1';      
      start_conv_in <= '0';
      bin <= 0;   
      wait for 20ns;
      
      rst_in <= '0';
      wait for 20ns;
      
      start_conv_in <= '1';
      wait for 10ns;
      start_conv_in <= '0';
      wait for 100ns;
      
      bin <= 24;  
      start_conv_in <= '1';
      wait for 100ns;
      
      bin <= 45;
      start_conv_in <= '1';
      wait for 10ns;
      start_conv_in <= '0';  
      wait for 100ns;
      
      bin <= 54;
      start_conv_in <= '1';
      wait for 10ns;
      start_conv_in <= '0';  
      wait for 100ns;
      
      bin <= 13;  -- NEEDS TO BE CAST TO STD LOGIC VECTOR
      start_conv_in <= '1';
      wait for 10ns;
      start_conv_in <= '0'; 
      wait for 100ns;
      
      bin <= 1; 
      start_conv_in <= '1';
      wait for 10ns;
      start_conv_in <= '0'; 
      wait for 100ns;
      
      wait;
  
  end process;
  
  bin_in <= to_unsigned(bin, bin_width);
END rtl;
