--
-- VHDL Test Bench DigTech4_lib.bin2bcd_tb.bin2bcd_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 12:39:36 02/04/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY bin2bcd_tb IS
   GENERIC (
      bin_width : integer := 6
   );
END bin2bcd_tb;


LIBRARY DigTech4_lib;
USE DigTech4_lib.ALL;


ARCHITECTURE rtl OF bin2bcd_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk_in        : std_logic;
   SIGNAL rst_in        : std_logic;
   SIGNAL start_conv_in : std_logic;
   SIGNAL bin_in        : unsigned(bin_width-1 downto 0);--std_logic_vector((bin_width-1) downto 0);
   SIGNAL conv_rdy_out  : std_logic;
   SIGNAL bcd_out       : unsigned(7 downto 0);--std_logic_vector(7 downto 0);


   -- Component declarations
   COMPONENT bin2bcd
      GENERIC (
         bin_width : integer := 6
      );
      PORT (
         clk_in        : IN     std_logic;
         rst_in        : IN     std_logic;
         start_conv_in : IN     std_logic;
         bin_in        : IN     unsigned(bin_width-1 downto 0);--std_logic_vector((bin_width-1) downto 0);
         conv_rdy_out  : OUT    std_logic;
         bcd_out       : OUT    unsigned(7 downto 0)--std_logic_vector(7 downto 0)
      );
   END COMPONENT;

   COMPONENT bin2bcd_tester
      GENERIC (
         bin_width : integer := 6
      );
      PORT (
         clk_in        : OUT    std_logic;
         rst_in        : OUT    std_logic;
         start_conv_in : OUT    std_logic;
         bin_in        : OUT    unsigned(bin_width-1 downto 0);--std_logic_vector((bin_width-1) downto 0);
         conv_rdy_out  : IN     std_logic;
         bcd_out       : IN     unsigned(7 downto 0)--std_logic_vector(7 downto 0)
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : bin2bcd USE ENTITY DigTech4_lib.bin2bcd;
   FOR U_1 : bin2bcd_tester USE ENTITY DigTech4_lib.bin2bcd_tester;
   -- pragma synthesis_on

BEGIN

         U_0 : bin2bcd
            GENERIC MAP (
               bin_width => bin_width
            )
            PORT MAP (
               clk_in        => clk_in,
               rst_in        => rst_in,
               start_conv_in => start_conv_in,
               bin_in        => bin_in,
               conv_rdy_out  => conv_rdy_out,
               bcd_out       => bcd_out
            );

         U_1 : bin2bcd_tester
            GENERIC MAP (
               bin_width => bin_width
            )
            PORT MAP (
               clk_in        => clk_in,
               rst_in        => rst_in,
               start_conv_in => start_conv_in,
               bin_in        => bin_in,
               conv_rdy_out  => conv_rdy_out,
               bcd_out       => bcd_out
            );


END rtl;