--
-- VHDL Test Bench DigTech4_lib.counter_tester.counter_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 16:16:36 29/03/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
--USE ieee.std_logic_arith.all;
use IEEE.numeric_std.all;


ENTITY counter_tester IS
   GENERIC (
      ctr_width : integer := 6;
      CTR_OVERFLOW_VALUE :  integer     := 60
   );
   PORT (
      clk_in          : OUT    std_logic;
      rst_in          : OUT    std_logic;
      enable_in       : OUT    std_logic;
      count_in:         OUT        std_logic; 
      updown_in       : out std_logic; 
      adjust_in       : OUT    std_logic;
      ctr_val_in      : OUT    unsigned(ctr_width-1 downto 0);--std_logic_vector(ctr_width-1 downto 0);
      ctr_comp_val_in : OUT    unsigned(ctr_width-1 downto 0);--std_logic_vector(ctr_width-1 downto 0);
      ctr_val_out     : IN     unsigned(ctr_width-1 downto 0);--std_logic_vector(ctr_width-1 downto 0);
      ctr_match_out   : IN     std_logic
   );
END counter_tester;


LIBRARY DigTech4_lib;

ARCHITECTURE rtl OF counter_tester IS
  signal ctr_comp_val, ctr_val: integer;
   -- Architecture declarations
BEGIN
  process begin
  while(true) loop
    clk_in <= '0';
    wait for 5ns;
    clk_in <= '1';
    wait for 5ns;
end loop;
wait;
  end process;

  process begin
   while(true) loop
     count_in <= '0';
     wait for 25ns;
     count_in <= '1';
     wait for 25ns;
 end loop;
 wait;
   end process;
  
  process begin  
      rst_in <= '1';      
      enable_in <= '0';   
      adjust_in <= '0';     
      updown_in <= '0';
      ctr_val <= 40;
      ctr_comp_val <= 59;
      wait for 20ns;
      rst_in <= '0';
      wait for 20ns;
      enable_in <= '1';
      wait for 200ns;
      adjust_in <= '1';
      wait for 20ns;
      adjust_in <= '0';
      wait for 20ns;
      updown_in <= '1';
      wait;
  
  end process;
  
  ctr_val_in <= to_unsigned(ctr_val, ctr_width);
  ctr_comp_val_in <= to_unsigned(ctr_comp_val, ctr_width);
END rtl;
