--
-- VHDL Test Bench DigTech4_lib.multicounter_tester.multicounter_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 13:56:47 19/04/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY multicounter_tester IS
   GENERIC (
      CTR_WIDTH          : integer := 6;
      CTR_OVERFLOW_VALUE : integer := ((2**6)-1)
   );
   PORT (
      clk_in          : OUT    std_logic;
      rst_in          : OUT    std_logic;
      enable_in       : OUT    std_logic;
      count_in        : OUT    std_logic;
      updown_in       : OUT    std_logic;
      adjust_in       : OUT    std_logic;
      ctr_val_in      : OUT    unsigned(CTR_WIDTH-1 downto 0);
      ctr_comp_val_in : OUT    unsigned(CTR_WIDTH-1 downto 0);
      ctr_val_out     : IN     unsigned(CTR_WIDTH-1 downto 0);
      ctr_match_out   : IN     std_logic;
      ctr_overfl_out  : IN     std_logic
   );
END multicounter_tester;


LIBRARY DigTech4_lib;

ARCHITECTURE rtl OF multicounter_tester IS
signal ctr_comp_val, ctr_val: integer;
-- Architecture declarations
BEGIN
process begin
while(true) loop
 clk_in <= '0';
 count_in <= '0';
 wait for 5ns;
 clk_in <= '1';
 count_in <= '1';
 wait for 5ns;
end loop;
wait;
end process;

process begin  
   rst_in <= '1';      
   enable_in <= '0';   
   adjust_in <= '0';     
   updown_in <= '0';
   ctr_val <= 40;
   ctr_comp_val <= 59;
   wait for 20ns;
   rst_in <= '0';
   wait for 20ns;
   enable_in <= '1';
   wait for 200ns;
   adjust_in <= '1';
   wait for 20ns;
   adjust_in <= '0';
   wait for 20ns;
   updown_in <= '1';
   wait;

end process;

ctr_val_in <= to_unsigned(ctr_val, ctr_width);
ctr_comp_val_in <= to_unsigned(ctr_comp_val, ctr_width);
END rtl;
