--
-- VHDL Test Bench DigTech4_lib.multicounter_tb.multicounter_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 13:56:46 19/04/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY multicounter_tb IS
   GENERIC (
      CTR_WIDTH          : integer := 6;
      CTR_OVERFLOW_VALUE : integer := ((2**6)-1)
   );
END multicounter_tb;


LIBRARY DigTech4_lib;
USE DigTech4_lib.ALL;


ARCHITECTURE rtl OF multicounter_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk_in          : std_logic;
   SIGNAL rst_in          : std_logic;
   SIGNAL enable_in       : std_logic;
   SIGNAL count_in        : std_logic;
   SIGNAL updown_in       : std_logic;
   SIGNAL adjust_in       : std_logic;
   SIGNAL ctr_val_in      : unsigned(CTR_WIDTH-1 downto 0);
   SIGNAL ctr_comp_val_in : unsigned(CTR_WIDTH-1 downto 0);
   SIGNAL secs_val, mins_val, hrs_val     : unsigned(CTR_WIDTH-1 downto 0);
   signal secs_OVF, mins_OVF, hrs_OVF : std_logic;


   -- Component declarations
   COMPONENT counter
      GENERIC (
         CTR_WIDTH          : integer := 6;
         CTR_OVERFLOW_VALUE : integer := ((2**6)-1)
      );
      PORT (
         clk_in          : IN     std_logic;
         rst_in          : IN     std_logic;
         enable_in       : IN     std_logic;
         count_in        : IN     std_logic;
         updown_in       : IN     std_logic;
         adjust_in       : IN     std_logic;
         ctr_val_in      : IN     unsigned(CTR_WIDTH-1 downto 0);
         ctr_comp_val_in : IN     unsigned(CTR_WIDTH-1 downto 0);
         ctr_val_out     : OUT    unsigned(CTR_WIDTH-1 downto 0);
         ctr_match_out   : OUT    std_logic;
         ctr_overfl_out  : OUT    std_logic
      );
   END COMPONENT;

   COMPONENT multicounter_tester
      GENERIC (
         CTR_WIDTH          : integer := 6;
         CTR_OVERFLOW_VALUE : integer := ((2**6)-1)
      );
      PORT (
         clk_in          : OUT    std_logic;
         rst_in          : OUT    std_logic;
         enable_in       : OUT    std_logic;
         count_in        : OUT    std_logic;
         updown_in       : OUT    std_logic;
         adjust_in       : OUT    std_logic;
         ctr_val_in      : OUT    unsigned(CTR_WIDTH-1 downto 0);
         ctr_comp_val_in : OUT    unsigned(CTR_WIDTH-1 downto 0);
         ctr_val_out     : IN     unsigned(CTR_WIDTH-1 downto 0);
         ctr_match_out   : IN     std_logic;
         ctr_overfl_out  : IN     std_logic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR SECS, MINS, HRS : counter USE ENTITY DigTech4_lib.counter;
   FOR U_1 : multicounter_tester USE ENTITY DigTech4_lib.multicounter_tester;
   -- pragma synthesis_on

BEGIN

         SECS : counter
            GENERIC MAP (
               CTR_WIDTH          => CTR_WIDTH,
               CTR_OVERFLOW_VALUE => 59
            )
            PORT MAP (
               clk_in          => clk_in,
               rst_in          => rst_in,
               enable_in       => enable_in,
               count_in        => count_in,
               updown_in       => '0',
               adjust_in       => '0',
               ctr_val_in      => ctr_val_in,
               ctr_comp_val_in => ctr_comp_val_in,
               ctr_val_out     => secs_val,
               --ctr_match_out   => ctr_match_out,
               ctr_overfl_out  => secs_OVF
            );

            MINS : counter
            GENERIC MAP (
               CTR_WIDTH          => CTR_WIDTH,
               CTR_OVERFLOW_VALUE => 59
            )
            PORT MAP (
               clk_in          => clk_in,
               rst_in          => rst_in,
               enable_in       => enable_in,
               count_in        => secs_OVF,
               updown_in       => '0',
               adjust_in       => '0',
               ctr_val_in      => ctr_val_in,
               ctr_comp_val_in => ctr_comp_val_in,
               ctr_val_out     => mins_val,
               --ctr_match_out   => ctr_match_out,
               ctr_overfl_out  => mins_OVF
            );
            
            HRS : counter
            GENERIC MAP (
               CTR_WIDTH          => CTR_WIDTH,
               CTR_OVERFLOW_VALUE => 23
            )
            PORT MAP (
               clk_in          => clk_in,
               rst_in          => rst_in,
               enable_in       => enable_in,
               count_in        => mins_OVF,
               updown_in       => '0',
               adjust_in       => '0',
               ctr_val_in      => ctr_val_in,
               ctr_comp_val_in => ctr_comp_val_in,
               ctr_val_out     => hrs_val,
               --ctr_match_out   => ctr_match_out,
               ctr_overfl_out  => hrs_OVF
            );

         U_1 : multicounter_tester
            GENERIC MAP (
               CTR_WIDTH          => CTR_WIDTH,
               CTR_OVERFLOW_VALUE => CTR_OVERFLOW_VALUE
            )
            PORT MAP (
               clk_in          => clk_in,
               rst_in          => rst_in,
               enable_in       => enable_in,
               count_in        => count_in,
               updown_in       => updown_in,
               adjust_in       => adjust_in,
               ctr_val_in      => ctr_val_in,
               ctr_comp_val_in => ctr_comp_val_in,
               ctr_val_out     => "000000",
               ctr_match_out   => '0',
               ctr_overfl_out  => '0'
            );


END rtl;