--
-- VHDL Test Bench DigTech4_lib.wekker_tester.wekker_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 15:51:59 15/04/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY wekker_tester IS
   GENERIC (
      SW_ADJ_RUN   : std_logic_vector(1 downto 0) := "00";
      SW_ADJ_TIME  : std_logic_vector(1 downto 0) := "10";
      SW_ADJ_ALARM : std_logic_vector(1 downto 0) := "01";
      DB_SAMPLES   : integer                      := 20
   );
   PORT (
      clock_in           : OUT    std_logic;
      alarm_in           : OUT    std_logic;
      adjust_in          : OUT    std_logic_vector(1 downto 0);
      snooze_in          : OUT    std_logic;
      minute_in          : OUT    std_logic;
      hour_in            : OUT    std_logic;
      d_select_in        : OUT    std_logic;
      buzz_out           : IN     std_logic;
      display_data_out   : IN     unsigned(3 downto 0);
      display_select_out : IN     std_logic_vector(3 downto 0);
      led_out            : IN     std_logic
   );
END wekker_tester;


LIBRARY DigTech4_lib;

ARCHITECTURE rtl OF wekker_tester IS
   -- Architecture declarations
BEGIN
   -- standard clk '1hz'
   process begin
      while(true) loop
         clock_in <= '0';
         wait for 100ns;
         clock_in <= '1';
         wait for 100ns;
      end loop;
      wait;
   end process;

   -- d_select clk 1024hz
   process begin
      while(true) loop
         d_select_in <= '0';
         wait for 1ns;
         d_select_in <= '1';
         wait for 1ns;
      end loop;
      wait;
   end process;
   
   --Time (“10”)
   --Run (“00”)
   --Alarm (“01”)

   process begin  
      alarm_in <= '0';
      adjust_in <= "00";
      snooze_in <= '0';
      minute_in <= '0';
      hour_in <= '0';
      wait for 100ms;
      adjust_in <= "10";
      wait for 1ms;
      minute_in <= '1';
      hour_in <= '1';
      wait for 500ns;
      minute_in <= '0';
      hour_in <= '0';
      wait for 500ns;
      for i in 0 to 100 loop
         minute_in <= '1';
         wait for 500ns;
         minute_in <= '0'
         wait for 500ns;
       end loop;
      adjust_in <= "00";
      wait for 1ms;
      adjust_in <= "01";
      wait for 1ms;
      for i in 0 to 30 loop
         hour_in <= '1';
         wait for 500ns;
         hour_in <= '0'
         wait for 500ns;
       end loop;
      adjust_in <= "00";
      wait for 1ms;
      alarm_in <= '1';
      wait for 1000ms;

      while(true) loop
         snooze_in <= '1';
         wait for 10ms;
         snooze_in <= '0';
         wait;
      end loop;

   end process;
END rtl;
