--
-- VHDL Test Bench DigTech4_lib.wekker_tb.wekker_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 15:51:59 15/04/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY wekker_tb IS
   GENERIC (
      SW_ADJ_RUN   : std_logic_vector(1 downto 0) := "00";
      SW_ADJ_TIME  : std_logic_vector(1 downto 0) := "10";
      SW_ADJ_ALARM : std_logic_vector(1 downto 0) := "01";
      DB_SAMPLES   : integer                      := 20
   );
END wekker_tb;


LIBRARY DigTech4_lib;
USE DigTech4_lib.ALL;


ARCHITECTURE rtl OF wekker_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clock_1hz_in           : std_logic;
   SIGNAL alarm_in           : std_logic;
   SIGNAL adjust_in          : std_logic_vector(1 downto 0);
   SIGNAL snooze_in          : std_logic;
   SIGNAL minute_in          : std_logic;
   SIGNAL hour_in            : std_logic;
   SIGNAL d_select_in        : std_logic;
   SIGNAL buzz_out           : std_logic;
   SIGNAL display_data_out   : unsigned(3 downto 0);
   SIGNAL display_select_out : std_logic_vector(3 downto 0);
   SIGNAL led_out            : std_logic;


   -- Component declarations
   COMPONENT wekker
      GENERIC (
         SW_ADJ_RUN   : std_logic_vector(1 downto 0) := "00";
         SW_ADJ_TIME  : std_logic_vector(1 downto 0) := "10";
         SW_ADJ_ALARM : std_logic_vector(1 downto 0) := "01";
         DB_SAMPLES   : integer                      := 20
      );
      PORT (
         clock_1hz_in           : IN     std_logic;
         alarm_in           : IN     std_logic;
         adjust_in          : IN     std_logic_vector(1 downto 0);
         snooze_in          : IN     std_logic;
         minute_in          : IN     std_logic;
         hour_in            : IN     std_logic;
         d_select_in        : IN     std_logic;
         buzz_out           : OUT    std_logic;
         display_data_out   : OUT    unsigned(3 downto 0);
         display_select_out : OUT    std_logic_vector(3 downto 0);
         led_out            : OUT    std_logic
      );
   END COMPONENT;

   COMPONENT wekker_tester
      GENERIC (
         SW_ADJ_RUN   : std_logic_vector(1 downto 0) := "00";
         SW_ADJ_TIME  : std_logic_vector(1 downto 0) := "10";
         SW_ADJ_ALARM : std_logic_vector(1 downto 0) := "01";
         DB_SAMPLES   : integer                      := 20
      );
      PORT (
         clock_1hz_in           : OUT    std_logic;
         alarm_in           : OUT    std_logic;
         adjust_in          : OUT    std_logic_vector(1 downto 0);
         snooze_in          : OUT    std_logic;
         minute_in          : OUT    std_logic;
         hour_in            : OUT    std_logic;
         d_select_in        : OUT    std_logic;
         buzz_out           : IN     std_logic;
         display_data_out   : IN     unsigned(3 downto 0);
         display_select_out : IN     std_logic_vector(3 downto 0);
         led_out            : IN     std_logic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR DUT_0 : wekker USE ENTITY DigTech4_lib.wekker;
   FOR U_1 : wekker_tester USE ENTITY DigTech4_lib.wekker_tester;
   -- pragma synthesis_on

BEGIN

        DUT_0 : wekker
            GENERIC MAP (
               SW_ADJ_RUN   => SW_ADJ_RUN,
               SW_ADJ_TIME  => SW_ADJ_TIME,
               SW_ADJ_ALARM => SW_ADJ_ALARM,
               DB_SAMPLES   => DB_SAMPLES
            )
            PORT MAP (
               clock_1hz_in           => clock_1hz_in,
               alarm_in           => alarm_in,
               adjust_in          => adjust_in,
               snooze_in          => snooze_in,
               minute_in          => minute_in,
               hour_in            => hour_in,
               d_select_in        => d_select_in,
               buzz_out           => buzz_out,
               display_data_out   => display_data_out,
               display_select_out => display_select_out,
               led_out            => led_out
            );

         U_1 : wekker_tester
            GENERIC MAP (
               SW_ADJ_RUN   => SW_ADJ_RUN,
               SW_ADJ_TIME  => SW_ADJ_TIME,
               SW_ADJ_ALARM => SW_ADJ_ALARM,
               DB_SAMPLES   => DB_SAMPLES
            )
            PORT MAP (
               clock_1hz_in           => clock_1hz_in,
               alarm_in           => alarm_in,
               adjust_in          => adjust_in,
               snooze_in          => snooze_in,
               minute_in          => minute_in,
               hour_in            => hour_in,
               d_select_in        => d_select_in,
               buzz_out           => buzz_out,
               display_data_out   => display_data_out,
               display_select_out => display_select_out,
               led_out            => led_out
            );


END rtl;