--
-- VHDL Test Bench DigTech4_lib.mux_control_tester.mux_control_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 13:51:40 03/04/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY mux_control_tester IS
   GENERIC (
      data_width : integer := 4
   );
   PORT (
      clk_in       : OUT    std_logic;
      rst_in       : OUT    std_logic;
      en_in        : OUT    std_logic;
      data_1_in    : OUT    unsigned(data_width-1 downto 0);
      data_2_in    : OUT    unsigned(data_width-1 downto 0);
      data_3_in    : OUT    unsigned(data_width-1 downto 0);
      data_4_in    : OUT    unsigned(data_width-1 downto 0);
      data_out     : IN     unsigned(data_width-1 downto 0);
      outp_sel_out : IN     std_logic_vector(3 downto 0)
   );
END mux_control_tester;


LIBRARY DigTech4_lib;

ARCHITECTURE rtl OF mux_control_tester IS
   -- Architecture declarations
BEGIN
process begin
   while(true) loop
     clk_in <= '0';
     wait for 5ns;
     clk_in <= '1';
     wait for 5ns;
 end loop;
 wait;
   end process;
   
   process begin  
       rst_in <= '1';      
       en_in <= '0';      
       data_1_in <= "1110";  
       data_2_in <= "1101";  
       data_3_in <= "1011";  
       data_4_in <= "0111";  
       wait for 20ns;
       rst_in <= '0';
       wait for 20ns;
       en_in <= '1';
       wait for 20ns;
       wait;
   
   end process;




END rtl;
