--
-- VHDL Test Bench DigTech4_lib.debouncer_tester.debouncer_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 15:41:05 08/04/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ENTITY debouncer_tester IS
   GENERIC (
      samples : integer := 20
   );
   PORT (
      clk_in : OUT    std_logic;
      rst_in : OUT    std_logic;
      s_in   : OUT    std_logic;
      db_out : IN     std_logic
   );
END debouncer_tester;


LIBRARY DigTech4_lib;

ARCHITECTURE rtl OF debouncer_tester IS
   -- Architecture declarations
BEGIN
  process begin
  while(true) loop
    clk_in <= '0';
    wait for 1ns;
    clk_in <= '1';
    wait for 1ns;
end loop;
wait;
  end process;
  
  process begin  
      rst_in <= '1';
      s_in <= '0';        
      wait for 20ns;
      rst_in <= '0';
      wait for 50ns;
      s_in <= '1';  
      wait for 5ns;
      s_in <= '0'; 
      wait for 50ns;
      s_in <= '1';  
      wait for 100ns;
      s_in <= '0'; 
      wait for 100ns;
      wait;
  
  end process;
END rtl;
