--
-- VHDL Test Bench DigTech4_lib.counter_tb.counter_tester
--
-- Created:
--          by - laure.UNKNOWN (CRAPTOP)
--          at - 16:16:35 29/03/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.1 Built on 21 Jan 2022 at 13:00:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY counter_tb IS
   GENERIC (
      ctr_width : integer := 6
   );
END counter_tb;


LIBRARY DigTech4_lib;
USE DigTech4_lib.ALL;


ARCHITECTURE rtl OF counter_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk_in          : std_logic;
   SIGNAL rst_in          : std_logic;
   SIGNAL enable_in       : std_logic;
   SIGNAL adjust_in       : std_logic;
   SIGNAL ctr_val_in      : std_logic_vector(ctr_width-1 downto 0);
   SIGNAL ctr_comp_val_in : std_logic_vector(ctr_width-1 downto 0);
   SIGNAL ctr_val_out     : std_logic_vector(ctr_width-1 downto 0);
   SIGNAL ctr_match_out   : std_logic;


   -- Component declarations
   COMPONENT counter
      GENERIC (
         ctr_width : integer := 6
      );
      PORT (
         clk_in          : IN     std_logic;
         rst_in          : IN     std_logic;
         enable_in       : IN     std_logic;
         adjust_in       : IN     std_logic;
         ctr_val_in      : IN     std_logic_vector(ctr_width-1 downto 0);
         ctr_comp_val_in : IN     std_logic_vector(ctr_width-1 downto 0);
         ctr_val_out     : OUT    std_logic_vector(ctr_width-1 downto 0);
         ctr_match_out   : OUT    std_logic
      );
   END COMPONENT;

   COMPONENT counter_tester
      GENERIC (
         ctr_width : integer := 6
      );
      PORT (
         clk_in          : OUT    std_logic;
         rst_in          : OUT    std_logic;
         enable_in       : OUT    std_logic;
         adjust_in       : OUT    std_logic;
         ctr_val_in      : OUT    std_logic_vector(ctr_width-1 downto 0);
         ctr_comp_val_in : OUT    std_logic_vector(ctr_width-1 downto 0);
         ctr_val_out     : IN     std_logic_vector(ctr_width-1 downto 0);
         ctr_match_out   : IN     std_logic
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : counter USE ENTITY DigTech4_lib.counter;
   FOR U_1 : counter_tester USE ENTITY DigTech4_lib.counter_tester;
   -- pragma synthesis_on

BEGIN

         U_0 : counter
            GENERIC MAP (
               ctr_width => ctr_width
            )
            PORT MAP (
               clk_in          => clk_in,
               rst_in          => rst_in,
               enable_in       => enable_in,
               adjust_in       => adjust_in,
               ctr_val_in      => ctr_val_in,
               ctr_comp_val_in => ctr_comp_val_in,
               ctr_val_out     => ctr_val_out,
               ctr_match_out   => ctr_match_out
            );

         U_1 : counter_tester
            GENERIC MAP (
               ctr_width => ctr_width
            )
            PORT MAP (
               clk_in          => clk_in,
               rst_in          => rst_in,
               enable_in       => enable_in,
               adjust_in       => adjust_in,
               ctr_val_in      => ctr_val_in,
               ctr_comp_val_in => ctr_comp_val_in,
               ctr_val_out     => ctr_val_out,
               ctr_match_out   => ctr_match_out
            );


END rtl;